-- R&R Fabrication Project Tracker
-- PostgreSQL schema, version 2
-- Seven tables: users, projects, stage_history, deliveries,
-- change_orders, invoices, documents
--
-- Notes:
--  * IDs are UUIDs generated by the database (clean keys for the future CRM).
--  * Money is numeric(14,2) so cents never drift.
--  * Dates that are day-only use `date`; timestamps use `timestamptz`.
--  * Projects are archived (is_archived), never hard-deleted.
--  * crm_customer_id and bid_id are reserved for a future tie-in to the CRM
--    and bid tool. They stay blank until that integration is built.
--  * Computed billing figures (earned less retainage, previous payments,
--    current payment due, project totals) are NOT stored. They are added up
--    from the invoices at read time so they are always correct.

CREATE EXTENSION IF NOT EXISTS pgcrypto;  -- provides gen_random_uuid()

-- ---------------------------------------------------------------------------
-- USERS
-- Each person logs in separately. Role drives what they can see and do.
-- ---------------------------------------------------------------------------
CREATE TABLE users (
    id            uuid PRIMARY KEY DEFAULT gen_random_uuid(),
    name          text        NOT NULL,
    email         text        NOT NULL UNIQUE,
    password_hash text        NOT NULL,
    role          text        NOT NULL
                  CHECK (role IN ('super_admin','admin','accounting','pm','shop')),
    is_active     boolean     NOT NULL DEFAULT true,
    created_at    timestamptz NOT NULL DEFAULT now()
);

-- Only one Super Admin is ever allowed.
CREATE UNIQUE INDEX one_super_admin ON users (role) WHERE role = 'super_admin';

-- ---------------------------------------------------------------------------
-- PROJECTS
-- The heart of the app. Keeps the fields the current tracker already has,
-- plus archive flag, created_by, and reserved CRM / bid reference columns.
-- Billing/retainage live in invoices; change-order dollars in change_orders.
-- ---------------------------------------------------------------------------
CREATE TABLE projects (
    id                  uuid PRIMARY KEY DEFAULT gen_random_uuid(),
    job_number          text,
    name                text        NOT NULL,
    customer            text,
    original_contract   numeric(14,2),     -- starting contract amount (old sell_price)
    cost                numeric(14,2),
    pm                  text,              -- label for now; can link to users later
    status              text        NOT NULL DEFAULT 'Bidding'
                        CHECK (status IN (
                            'Bidding','Submitted','Awarded','Purchasing',
                            'In Fabrication','Ready for Galvanizing/Paint',
                            'In Galvanizing','In Paint','Shipping',
                            'Field/Erection','Completed','Lost/On Hold')),
    drawing_status      text        NOT NULL DEFAULT 'N/A'
                        CHECK (drawing_status IN (
                            'N/A','Not Started','In Progress',
                            'Approved','Revision Needed')),
    -- phase dates carried over from the current app
    bid_due_date        date,
    submitted_date      date,
    award_date          date,
    project_start_date  date,
    fab_start_date      date,
    galv_send_date      date,
    galv_return_date    date,
    paint_send_date     date,
    paint_complete_date date,
    needs_setup         boolean     NOT NULL DEFAULT false,  -- true on jobs imported from the bid tool until someone fills in the planning dates
    material_ordered    boolean     NOT NULL DEFAULT false,
    notes               text,
    is_archived         boolean     NOT NULL DEFAULT false,
    crm_customer_id     uuid,              -- reserved: future CRM customer link (blank for now)
    bid_id              uuid,              -- reserved: future bid-tool link (blank for now)
    created_by          uuid        REFERENCES users(id),
    created_at          timestamptz NOT NULL DEFAULT now(),
    updated_at          timestamptz NOT NULL DEFAULT now()
);

-- ---------------------------------------------------------------------------
-- STAGE_HISTORY
-- One row every time a project's status changes. The audit trail behind the
-- live status on the project.
-- ---------------------------------------------------------------------------
CREATE TABLE stage_history (
    id          uuid PRIMARY KEY DEFAULT gen_random_uuid(),
    project_id  uuid        NOT NULL REFERENCES projects(id) ON DELETE CASCADE,
    status      text        NOT NULL,
    changed_by  uuid        REFERENCES users(id),
    changed_at  timestamptz NOT NULL DEFAULT now()
);
CREATE INDEX idx_stage_history_project ON stage_history (project_id);

-- ---------------------------------------------------------------------------
-- DELIVERIES
-- Delivery phases, pulled out of the old JSON column into real rows.
-- ---------------------------------------------------------------------------
CREATE TABLE deliveries (
    id            uuid PRIMARY KEY DEFAULT gen_random_uuid(),
    project_id    uuid        NOT NULL REFERENCES projects(id) ON DELETE CASCADE,
    delivery_date date,
    description   text,
    done          boolean     NOT NULL DEFAULT false,
    done_at       timestamptz,
    sort_order    integer
);
CREATE INDEX idx_deliveries_project ON deliveries (project_id);

-- ---------------------------------------------------------------------------
-- CHANGE_ORDERS
-- Every C/O on a job. Only Approved or Paid C/Os grow the contract sum
-- (that math happens in the app, summing this table).
-- ---------------------------------------------------------------------------
CREATE TABLE change_orders (
    id             uuid PRIMARY KEY DEFAULT gen_random_uuid(),
    project_id     uuid        NOT NULL REFERENCES projects(id) ON DELETE CASCADE,
    co_number      text        NOT NULL,
    description    text,
    amount         numeric(14,2) NOT NULL DEFAULT 0,  -- negative allowed for a credit
    status         text        NOT NULL DEFAULT 'Pending'
                   CHECK (status IN ('Pending','Approved','Paid')),
    submitted_date date,
    approved_date  date,
    paid_date      date,
    created_by     uuid        REFERENCES users(id),
    created_at     timestamptz NOT NULL DEFAULT now()
);
CREATE INDEX idx_change_orders_project ON change_orders (project_id);

-- ---------------------------------------------------------------------------
-- INVOICES (AIA pay applications)
-- One row per pay app. The dollar fields below are what a person enters;
-- earned-less-retainage, previous payments, and current payment due are
-- calculated by the app and not stored.
-- ---------------------------------------------------------------------------
CREATE TABLE invoices (
    id                     uuid PRIMARY KEY DEFAULT gen_random_uuid(),
    project_id             uuid        NOT NULL REFERENCES projects(id) ON DELETE CASCADE,
    application_number     integer     NOT NULL,
    period_end             date,
    work_completed_to_date numeric(14,2) NOT NULL DEFAULT 0,
    retainage_pct          numeric(5,2)  NOT NULL DEFAULT 10,  -- can change app to app
    retainage_held         numeric(14,2),                      -- optional override for
                                                               -- variable / stored-material
                                                               -- retainage; if null the app
                                                               -- computes completed * pct
    amount_paid            numeric(14,2),                      -- what actually landed
    is_retainage_release   boolean     NOT NULL DEFAULT false,  -- final app that bills
                                                               -- out the held retainage
    status                 text        NOT NULL DEFAULT 'Draft'
                           CHECK (status IN ('Draft','Submitted','Approved','Partially Paid','Paid')),
    submitted_date         date,
    approved_date          date,
    paid_date              date,
    notes                  text,
    created_by             uuid        REFERENCES users(id),
    created_at             timestamptz NOT NULL DEFAULT now(),
    UNIQUE (project_id, application_number)  -- no duplicate app numbers per job
);
CREATE INDEX idx_invoices_project ON invoices (project_id);

-- ---------------------------------------------------------------------------
-- DOCUMENTS
-- File records. The file itself lives in object storage; this row holds the
-- metadata and a link. Always tied to a project; optionally to a specific
-- change order or pay app.
-- ---------------------------------------------------------------------------
CREATE TABLE documents (
    id              uuid PRIMARY KEY DEFAULT gen_random_uuid(),
    project_id      uuid        NOT NULL REFERENCES projects(id) ON DELETE CASCADE,
    change_order_id uuid        REFERENCES change_orders(id) ON DELETE CASCADE,
    invoice_id      uuid        REFERENCES invoices(id) ON DELETE CASCADE,
    file_name       text        NOT NULL,
    file_type       text,
    file_size       bigint,
    storage_key     text        NOT NULL,   -- pointer to the stored file
    category        text,                   -- e.g. 'C/O backup', 'pay app', 'drawing', 'general'
    uploaded_by     uuid        REFERENCES users(id),
    uploaded_at     timestamptz NOT NULL DEFAULT now()
);
CREATE INDEX idx_documents_project       ON documents (project_id);
CREATE INDEX idx_documents_change_order  ON documents (change_order_id);
CREATE INDEX idx_documents_invoice       ON documents (invoice_id);
